services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: myshopdb
            MYSQL_USER: admin
        container_name: mysql-bun
        ports:
            - '3306:3306'
        volumes:
            - ./db-init:/docker-entrypoint-initdb.d
        networks:
            - bun-mysql-network
    bunapp:
        build: .
        image: oven/bun
        ports:
            - '3001:3001'
        depends_on:
            - mysql
        environment:
            DB_HOST: mysql
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: myshopdb
            DB_PORT: 3306
        networks:
            - bun-mysql-network

networks:
    bun-mysql-network:
        driver: bridge
